version: '3.8'

services:
  app:
    build:
      context: ./docker
    volumes:
      - ./var/www
    depends_on:
      - mysql
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Isso expõe a porta do Nginx para o localhost
    volumes:
      - ./DashboardFinanceiro:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sua senha"
      MYSQL_DATABASE: "sua base de dados"
      MYSQL_USER: "usuário"
      MYSQL_PASSWORD: "sua senha"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  mysql-data:
